services:
  openldap:
    image: bitnami/openldap:2
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ROOT=dc=example,dc=org
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user-1,user-2,user-3,user-4
      - LDAP_PASSWORDS=password1,password2,password3,password4
      - LDAP_PORT_NUMBER=1389
